services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - 27017:27017
    networks:
      - payment_network
    environment:
      MONGO_INITDB_DATABASE: stripe
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./database:/usr/src/app
networks:
  payment_network:
    driver: bridge